name: Build Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Signed APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > intermit-release.keystore

      - name: Create local.properties
        run: |
          echo "storeFile=intermit-release.keystore" >> local.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> local.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> local.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build signed APK
        run: ./gradlew assembleRelease

      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: intermit-release-apk
          path: app/build/outputs/apk/release/app-release.apk
