name: Build Release APK

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build Signed APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > intermit-release.keystore

      - name: Export environment variables
        run: |
          echo "KEYSTORE_PATH=$(pwd)/intermit-release.keystore" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build signed APK
        run: ./gradlew assembleRelease

      - name: Get versionName from Gradle
        id: get_version
        run: |
          VERSION_NAME=$(./gradlew -q printVersionName)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Rename APK with version
        run: |
          mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/intermit-v${{ env.VERSION_NAME }}.apk

      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: intermit-release-apk
          path: app/build/outputs/apk/release/intermit-v${{ env.VERSION_NAME }}.apk
